### ISSUE TITLE
not supported in sonarqube 7.6 version

### ISSUE THREAD

**Issue by ChenGuanqun** [thienan93/phdiff#7]
Hi,

I have tried to integrate this plugin with Jenkins  and phabricator. The analysis results were uploaded to sonar server successfully.

However, errors occurred at the end of the execution in Jenkins job, and no scan results comments sent to phabricator. 

[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.0.1398:sonar (default-cli) on project xxx: io.nthienan.phdiff.PhabricatorDifferentialPostJob has unsatisfied dependency 'class io.nthienan.phdiff.Configuration' for constructor 'public io.nthienan.phdiff.PhabricatorDifferentialPostJob(io.nthienan.phdiff.report.GlobalReportBuilder,io.nthienan.phdiff.report.InlineReportBuilder,io.nthienan.phdiff.Configuration)' from org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@6201a108:311<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@601e4250:50<| -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.0.1398:sonar (default-cli) on project xxx: io.nthienan.phdiff.PhabricatorDifferentialPostJob has unsatisfied dependency 'class io.nthienan.phdiff.Configuration' for constructor 'public io.nthienan.phdiff.PhabricatorDifferentialPostJob(io.nthienan.phdiff.report.GlobalReportBuilder,io.nthienan.phdiff.report.InlineReportBuilder,io.nthienan.phdiff.Configuration)' from org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@6201a108:311<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@601e4250:50<|
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: io.nthienan.phdiff.PhabricatorDifferentialPostJob has unsatisfied dependency 'class io.nthienan.phdiff.Configuration' for constructor 'public io.nthienan.phdiff.PhabricatorDifferentialPostJob(io.nthienan.phdiff.report.GlobalReportBuilder,io.nthienan.phdiff.report.InlineReportBuilder,io.nthienan.phdiff.Configuration)' from org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@6201a108:311<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@601e4250:50<|
	at org.sonarsource.scanner.maven.bootstrap.ScannerBootstrapper.execute(ScannerBootstrapper.java:67)
	at org.sonarsource.scanner.maven.SonarQubeMojo.execute(SonarQubeMojo.java:104)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: org.picocontainer.injectors.AbstractInjector$UnsatisfiableDependenciesException: io.nthienan.phdiff.PhabricatorDifferentialPostJob has unsatisfied dependency 'class io.nthienan.phdiff.Configuration' for constructor 'public io.nthienan.phdiff.PhabricatorDifferentialPostJob(io.nthienan.phdiff.report.GlobalReportBuilder,io.nthienan.phdiff.report.InlineReportBuilder,io.nthienan.phdiff.Configuration)' from org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@6201a108:311<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@601e4250:50<|
	at org.picocontainer.injectors.ConstructorInjector.getGreediestSatisfiableConstructor(ConstructorInjector.java:191)
	at org.picocontainer.injectors.ConstructorInjector.getGreediestSatisfiableConstructor(ConstructorInjector.java:110)
	at org.picocontainer.injectors.ConstructorInjector.access$100(ConstructorInjector.java:51)
	at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:331)
	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
	at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
	at org.picocontainer.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:606)
	at org.picocontainer.DefaultPicoContainer.getComponents(DefaultPicoContainer.java:587)
	at org.sonar.core.platform.ComponentContainer.getComponentsByType(ComponentContainer.java:290)
	at org.sonar.scanner.bootstrap.AbstractExtensionDictionnary.completeScannerExtensions(AbstractExtensionDictionnary.java:82)
	at org.sonar.scanner.bootstrap.AbstractExtensionDictionnary.getExtensions(AbstractExtensionDictionnary.java:77)
	at org.sonar.scanner.bootstrap.AbstractExtensionDictionnary.getFilteredExtensions(AbstractExtensionDictionnary.java:67)
	at org.sonar.scanner.bootstrap.PostJobExtensionDictionnary.selectPostJobs(PostJobExtensionDictionnary.java:42)
	at org.sonar.scanner.postjob.PostJobsExecutor.execute(PostJobsExecutor.java:38)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:327)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:128)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy23.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:185)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:137)
	at org.sonarsource.scanner.maven.bootstrap.ScannerBootstrapper.execute(ScannerBootstrapper.java:65)
	... 23 more

**Comment by ChenGuanqun** [comment]
Additional information:
sonarqube : Community EditionVersion 7.7 (build 23042)
jenkins: 2.164.1

maven config in jenkins jon:
sonar:sonar -X -s settings.xml -Dsonar.phdiff.diffId=${DIFF_ID} -Dsonar.login=4537ab1d270e9c8edc9700c4994c945fb785adc3 -Dsonar.host.url=http://10.130.64.225:31121/sonar

If -Dsonar.login and -Dsonar.host.url  removed as your guideline suggested, we got error and the execution failed soon. It seems the job tried to connect to localhost sonar server which is not existed.

**Comment by ChenGuanqun** [comment]
After rollback sonar server version to Version 6.7.6 (build 38781) - LGPL v3 - Community

The exception is gone, and sonar server sent comment  '**SonarQube has found no issue. You are great developer**'. However, **there are issues (2 bugs and 5 code smells) analyzed on sonar server**. It seems sonar server does not sent the real reports correctly to phabricator. 

@nthienan Can you please help to solve this problem. thanks

**Comment by ChenGuanqun** [comment]
We've resolved this issue with configuration set -Dsonar.analysis.mode=preview on sonarqube6.7, which is no longer supported in 7.6.  If this config is not set, the issues cannot be found, which is explained in the following code segment.

This plugin although need sonar.analysis.mode set to preview or issue.

   All the unresolved issues of the project, including the issues reported by end-users. **Only available in preview/issues mode.**
   @throw {@link UnsupportedOperationException} if not in preview/issues mode. To test the mode you can use {@link #analysisMode()}.
 
  Iterable<PostJobIssue> issues();

Close this issue.
