### ISSUE TITLE
sonarqube TaskExecutionException with 8.x

### ISSUE THREAD

**Issue by michaeloa** [thienan93/phdiff#8]
I'm trying to use this with Sonarqube 8.1.

Running gradlew sonarqube (without preview mode, as that is not supported in 8.x), I get a TaskExecutionException with 

`
Caused by: org.picocontainer.injectors.AbstractInjector$UnsatisfiableDependenciesException: io.nthienan.phdiff.PhabricatorDifferentialPostJob has unsatisfied dependency 'class io.nthienan.phdiff.Configuration' for constructor 'public io.nthienan.phdiff.PhabricatorDifferentialPostJob(io.nthienan.phdiff.report.GlobalReportBuilder,io.nthienan.phdiff.report.InlineReportBuilder,io.nthienan.phdiff.Configuration)' from org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@5d33480d:331<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@12d4b145:49<|
        at org.picocontainer.injectors.ConstructorInjector.getGreediestSatisfiableConstructor(ConstructorInjector.java:191)
        at org.picocontainer.injectors.ConstructorInjector.getGreediestSatisfiableConstructor(ConstructorInjector.java:110)
        at org.picocontainer.injectors.ConstructorInjector.access$100(ConstructorInjector.java:51)
        at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:331)
        at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
        at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
        at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
        at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
        at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
        at org.picocontainer.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:606)
        at org.picocontainer.DefaultPicoContainer.getComponents(DefaultPicoContainer.java:587)
        at org.sonar.core.platform.ComponentContainer.getComponentsByType(ComponentContainer.java:290)
        at org.sonar.scanner.bootstrap.AbstractExtensionDictionnary.completeScannerExtensions(AbstractExtensionDictionnary.java:82)
        at org.sonar.scanner.bootstrap.AbstractExtensionDictionnary.getExtensions(AbstractExtensionDictionnary.java:77)
        at org.sonar.scanner.bootstrap.AbstractExtensionDictionnary.getFilteredExtensions(AbstractExtensionDictionnary.java:67)
        at org.sonar.scanner.bootstrap.PostJobExtensionDictionnary.selectPostJobs(PostJobExtensionDictionnary.java:42)
        at org.sonar.scanner.postjob.PostJobsExecutor.execute(PostJobsExecutor.java:38)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:366)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
`

Any ideas?

**Comment by michaeloa** [comment]
Hmm.. downgraded to 7.9.2 because of issues with Java 11, but I'm still seeing the same problem.

**Comment by siepkes** [comment]
@michaeloa Bit late but for everyone stumbling across this; This plugin depends on the preview mode of SonarQube which was removed from SonarQube: https://jira.sonarsource.com/browse/SONAR-11670
